version: '3.8'

networks:
  gestao_vagas_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestao_vagas
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: gestao_vagas_prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gestao_vagas_network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: gestao_vagas_grafana
    volumes:
      - grafana_data:/grafana
    networks:
      - gestao_vagas_network
    ports:
      - "3000:3000"
