version: '3.8'

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestao_vagas
    ports:
      - "5432:5432"